"""Video annotator endpoints (session-based)."""

import os

from fastapi import APIRouter, HTTPException, Query
from fastapi.concurrency import run_in_threadpool
from fastapi.responses import Response
from pydantic import BaseModel

from api.services.annotate import video_service

router = APIRouter()


class OpenVideoRequest(BaseModel):
    video_path: str
    channel_handle: str | None = None


class DetectMovesRequest(BaseModel):
    sample_fps: float = 2.0
    clip_id: int | None = None
    reader_backend: str = "overlay"


class GenerateClipsRequest(BaseModel):
    clip_id: int | None = None


@router.post("/open")
async def open_video(body: OpenVideoRequest):
    """Open a video file and create an annotation session."""
    try:
        return await run_in_threadpool(
            video_service.open_video,
            body.video_path,
            body.channel_handle,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))


@router.get("/{session_id}/frame")
async def get_frame(session_id: str, index: int = Query(...)):
    """Get a single video frame as JPEG."""
    try:
        jpeg_bytes = await run_in_threadpool(
            video_service.get_frame_jpeg, session_id, index
        )
        return Response(content=jpeg_bytes, media_type="image/jpeg")
    except ValueError as e:
        raise HTTPException(404, str(e))


@router.get("/{session_id}/overlay-read")
async def read_overlay(
    session_id: str,
    index: int = Query(...),
    clip_id: int | None = Query(None),
    reader_backend: str = Query("overlay"),
):
    """Read overlay FEN at a specific frame."""
    try:
        return await run_in_threadpool(
            video_service.read_overlay_at_frame,
            session_id,
            index,
            clip_id,
            reader_backend,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))


@router.post("/{session_id}/detect-moves")
async def detect_moves(session_id: str, body: DetectMovesRequest):
    """Run full move detection on the video."""
    try:
        return await run_in_threadpool(
            video_service.detect_moves,
            session_id,
            body.sample_fps,
            body.clip_id,
            body.reader_backend,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))


@router.post("/{session_id}/detect-moves/jobs")
async def start_detect_moves_job(session_id: str, body: DetectMovesRequest):
    """Start move detection in the background."""
    try:
        return await run_in_threadpool(
            video_service.start_detect_moves_job,
            session_id,
            body.sample_fps,
            body.clip_id,
            body.reader_backend,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))


@router.get("/{session_id}/detect-moves/jobs/{job_id}")
async def get_detect_moves_job(session_id: str, job_id: str):
    """Poll background move-detection status."""
    result = await run_in_threadpool(video_service.get_detect_moves_job, job_id, session_id)
    if result is None:
        raise HTTPException(404, f"Job {job_id} not found")
    return result


@router.post("/{session_id}/generate-clips")
async def generate_clips(session_id: str, body: GenerateClipsRequest = GenerateClipsRequest()):
    """Generate training clips from this video session."""
    try:
        return await run_in_threadpool(
            video_service.generate_clips, session_id, body.clip_id
        )
    except ValueError as e:
        raise HTTPException(400, str(e))


@router.post("/{session_id}/generate-clips/jobs")
async def start_generate_clips_job(
    session_id: str, body: GenerateClipsRequest = GenerateClipsRequest()
):
    """Start clip generation in background and return job state."""
    try:
        return await run_in_threadpool(
            video_service.start_generate_clips_job, session_id, body.clip_id
        )
    except ValueError as e:
        raise HTTPException(400, str(e))


@router.get("/{session_id}/generate-clips/jobs/{job_id}")
async def get_generate_clips_job(session_id: str, job_id: str):
    """Poll generate-clips job status."""
    job = video_service.get_generate_clips_job(job_id)
    if job is None:
        raise HTTPException(404, "Job not found")
    return job


@router.get("/{session_id}/generated-clips")
async def list_generated_clips(session_id: str):
    """List .pt files generated by this session's video."""
    session = video_service._sessions.get(session_id)
    if session is None:
        raise HTTPException(404, "Session not found")

    import glob
    video_path = session["video_path"]
    video_id = os.path.splitext(os.path.basename(video_path))[0]

    from pipeline.overlay.overlay_clip_generator import OUTPUT_DIR
    pattern = os.path.join(OUTPUT_DIR, f"clip_overlay_{video_id}*.pt")
    clips = []
    for filepath in sorted(glob.glob(pattern)):
        clips.append({
            "filepath": filepath,
            "filename": os.path.basename(filepath),
        })
    return {"clips": clips}


@router.post("/{session_id}/generated-clips/save")
async def save_to_training(session_id: str, body: dict):
    """Copy a generated clip to the training data directory."""
    import shutil
    filepath = body.get("filepath")
    if not filepath or not os.path.exists(filepath):
        raise HTTPException(400, "File not found")

    dest_dir = os.path.join("data", "argus", "train_real")
    os.makedirs(dest_dir, exist_ok=True)
    dest = os.path.join(dest_dir, os.path.basename(filepath))
    shutil.copy2(filepath, dest)
    return {"saved": dest}


@router.delete("/{session_id}")
def delete_session(session_id: str):
    """Close a video session."""
    video_service.delete_session(session_id)
    return {"deleted": True}
