layouts:
  '@STLChessClub':
    overlay:
    - 0
    - 0
    - 1079
    - 1079
    camera:
    - 1079
    - 0
    - 841
    - 1080
    ref_resolution:
    - 1920
    - 1080
    board_flipped: false
    board_theme: lichess_default
    move_delay_seconds: 2.0
